import startCase from "lodash/startCase.js";

type SemanticLabel = {
    label: string;
    description?: string;
};

const LABELS: Record<string, SemanticLabel> = {
    action: { label: "动作", description: "设备上报的动作事件" },
    active_power: { label: "有功功率", description: "当前有功功率" },
    ac_frequency: { label: "交流频率" },
    admin: { label: "管理员" },
    air_quality: { label: "空气质量" },
    alarm: { label: "报警" },
    alarm_mode: { label: "报警模式" },
    alarm_ringtone: { label: "报警铃声" },
    alarm_set_1: { label: "报警设置 1" },
    alarm_set_2: { label: "报警设置 2" },
    alarm_set_3: { label: "报警设置 3" },
    alarm_status: { label: "报警状态" },
    algorithm: { label: "算法" },
    angle: { label: "角度" },
    angle_x: { label: "X 轴角度" },
    angle_y: { label: "Y 轴角度" },
    angle_x_absolute: { label: "X 轴绝对角度" },
    angle_y_absolute: { label: "Y 轴绝对角度" },
    angle_z: { label: "Z 轴角度" },
    approach_distance: { label: "接近距离" },
    aqi: { label: "空气质量指数" },
    area1Occupancy: { label: "区域 1 有人" },
    area2Occupancy: { label: "区域 2 有人" },
    area3Occupancy: { label: "区域 3 有人" },
    area4Occupancy: { label: "区域 4 有人" },
    auto_close_when_water_shortage: { label: "缺水自动关闭", description: "检测到缺水时自动关闭阀门" },
    automatic_mode: { label: "自动模式" },
    availability: { label: "在线状态" },
    away_mode: { label: "离家模式" },
    backlight: { label: "背光" },
    battery: { label: "电池电量", description: "电池剩余百分比" },
    battery_low: { label: "电量低", description: "是否处于低电量状态" },
    battery_state: { label: "电池状态" },
    beep: { label: "蜂鸣" },
    boost_heating: { label: "加速加热", description: "临时提高加热功率快速升温" },
    breaker: { label: "断路器" },
    brightness: { label: "亮度" },
    broadcast_alarm: { label: "广播报警" },
    buzzer: { label: "蜂鸣器" },
    cable_sensor_mode: { label: "线缆传感器模式" },
    cable_sensor_temperature: { label: "线缆传感器温度" },
    calibration: { label: "校准" },
    calibrate: { label: "执行校准" },
    carbon_monoxide: { label: "一氧化碳报警" },
    carbon_monoxide_value: { label: "一氧化碳浓度" },
    child_lock: { label: "童锁" },
    co2: { label: "二氧化碳" },
    co2_calibration: { label: "二氧化碳校准" },
    cold_water: { label: "冷水" },
    color: { label: "颜色" },
    color_hs: { label: "颜色 (HS)" },
    color_temp: { label: "色温" },
    color_temp_startup: { label: "上电色温" },
    color_mode: { label: "颜色模式", description: "当前灯光颜色模式" },
    color_sync: { label: "颜色同步", description: "同步多个灯具的颜色" },
    color_xy: { label: "颜色 (XY)" },
    config: { label: "配置" },
    compensation_coefficient: { label: "照度补偿系数", description: "用于修正照度检测值的补偿倍率" },
    contact: { label: "门窗状态", description: "门磁/窗磁开合状态" },
    control_algorithm: { label: "控制算法" },
    countdown: { label: "倒计时" },
    current: { label: "电流" },
    current_count: { label: "当前次数" },
    current_device_status: { label: "设备状态" },
    current_heating_setpoint: { label: "当前制热设定温度" },
    custom_system_mode: { label: "自定义系统模式" },
    cyclic_quantitative_irrigation: { label: "定量循环灌溉", description: "按固定水量循环灌溉" },
    cyclic_timed_irrigation: { label: "定时循环灌溉", description: "按固定时间循环灌溉" },
    data: { label: "数据" },
    data_report: { label: "数据上报" },
    dayTime: { label: "日间时间" },
    delay: { label: "延迟" },
    device_temperature: { label: "设备温度" },
    display_brightness: { label: "显示屏亮度" },
    display_switch_on_duration: { label: "屏幕亮起时长" },
    detection_area: { label: "检测区域" },
    detection_distance: { label: "检测距离", description: "人体存在雷达检测到的目标距离" },
    detection_range: { label: "检测范围" },
    direction: { label: "方向" },
    distance: { label: "距离" },
    door: { label: "门" },
    door_state: { label: "门状态" },
    duration: { label: "持续时间" },
    eco2: { label: "等效二氧化碳" },
    effect: { label: "灯效" },
    electric_valve: { label: "电动阀" },
    enabled: { label: "启用状态" },
    end_of_life: { label: "寿命到期" },
    energy: { label: "累计电量" },
    energy_balance: { label: "能量余额" },
    energy_balance_add: { label: "增加能量余额" },
    energy_balance_reset: { label: "重置能量余额" },
    energy_produced: { label: "发电量" },
    energy_reset: { label: "重置电量" },
    error: { label: "错误" },
    error_state: { label: "错误状态" },
    fan_mode: { label: "风速模式" },
    fault: { label: "故障" },
    faults: { label: "故障列表" },
    fading_time: { label: "无人延迟", description: "从有人变为无人前的延迟时间" },
    floor_temperature: { label: "地板温度" },
    flow: { label: "流量" },
    flow_switch: { label: "水流开关" },
    formaldehyd: { label: "甲醛" },
    force: { label: "力度" },
    forceupdate: { label: "强制更新" },
    free_chlorine: { label: "余氯" },
    frequency: { label: "频率" },
    friendly_name: { label: "设备名称", description: "Zigbee2MQTT 设备显示名，也是 MQTT topic 名的一部分" },
    frost: { label: "防冻" },
    garage_door: { label: "车库门" },
    gas: { label: "燃气报警" },
    gas_consumed: { label: "燃气用量" },
    gradient: { label: "渐变" },
    gradient_scene: { label: "渐变场景" },
    hcho: { label: "甲醛" },
    heartbeat: { label: "心跳" },
    heat_protect: { label: "过热保护" },
    heater_type: { label: "加热器类型" },
    heating_stop: { label: "停止加热" },
    hot_water: { label: "热水" },
    hold_timeout: { label: "长按超时", description: "判定为长按事件的时间阈值" },
    humidity_alarm: { label: "湿度报警" },
    humidity: { label: "湿度" },
    humidity_calibration: { label: "湿度校准" },
    humidity_precision: { label: "湿度精度" },
    illuminance: { label: "照度" },
    illuminance_calibration: { label: "照度校准" },
    illuminance_lux: { label: "照度" },
    illuminance_raw: { label: "原始照度" },
    identify: { label: "设备识别", description: "触发设备指示灯闪烁以便识别" },
    indicator: { label: "指示灯" },
    individual_led_effect: { label: "单灯珠效果" },
    interval: { label: "间隔" },
    ip_address: { label: "IP 地址" },
    irrigation: { label: "灌溉" },
    irrigation_capacity: { label: "灌溉水量" },
    irrigation_duration: { label: "灌溉时长" },
    irrigation_interval: { label: "灌溉间隔" },
    keypad: { label: "键盘" },
    keysound: { label: "按键音" },
    leak: { label: "漏水" },
    leakage: { label: "漏水" },
    leakage_current: { label: "漏电流" },
    led: { label: "指示灯" },
    led_disabled: { label: "禁用指示灯" },
    linkquality: { label: "信号质量", description: "Zigbee 链路质量，原始字段为 LQI/linkquality" },
    local_temperature: { label: "当前温度" },
    local_temperature_calibration: { label: "当前温度校准" },
    last_seen: { label: "最后上报", description: "最后一次收到设备消息的时间" },
    led_disabled_night: { label: "夜间禁用指示灯" },
    level_config: { label: "亮度配置" },
    max_temperature: { label: "最高温度" },
    melody: { label: "铃声" },
    meter_id: { label: "表计 ID" },
    min_temperature: { label: "最低温度" },
    moisture: { label: "湿度/含水量" },
    mode: { label: "模式" },
    model: { label: "型号" },
    motor_state: { label: "电机状态" },
    motor_reversal: { label: "电机反向" },
    movement: { label: "移动" },
    moving: { label: "移动状态" },
    no_occupancy_since: { label: "无人持续时间", description: "从最后一次检测到有人到现在的时间" },
    noise: { label: "噪声" },
    noise_detect_level: { label: "噪声检测阈值" },
    noise_detected: { label: "检测到噪声" },
    noise_timeout: { label: "噪声清除延迟" },
    occupancy_timeout: { label: "有人超时" },
    occupancy: { label: "有人状态", description: "人体存在/移动检测状态" },
    occupied_cooling_setpoint: { label: "制冷设定温度" },
    occupancy_level: { label: "有人检测强度" },
    occupancy_sensitivity: { label: "有人检测灵敏度" },
    occupied_heating_setpoint: { label: "制热设定温度" },
    operation_mode: { label: "操作模式" },
    operating_mode: { label: "运行模式" },
    orp: { label: "氧化还原电位" },
    over_voltage: { label: "过压" },
    overcurrent: { label: "过流" },
    overpower: { label: "过载功率" },
    percent: { label: "百分比" },
    percentage: { label: "百分比" },
    percent_state: { label: "百分比状态" },
    ph: { label: "PH 值" },
    pin_code: { label: "PIN 码" },
    pm10: { label: "PM10" },
    pm25: { label: "PM2.5" },
    position: { label: "开合位置" },
    power: { label: "功率" },
    power_factor: { label: "功率因数" },
    power_level: { label: "功率级别" },
    power_on_behavior: { label: "上电行为" },
    power_outage_count: { label: "断电次数" },
    power_outage_memory: { label: "断电记忆" },
    power_source: { label: "供电方式" },
    pressure: { label: "气压" },
    pressure_calibration: { label: "气压校准" },
    pressure_precision: { label: "气压精度" },
    presence: { label: "存在状态" },
    presence_switch: { label: "存在输出", description: "人体存在检测的继电器/输出开关" },
    produced_energy: { label: "发电量" },
    pump: { label: "水泵" },
    radar: { label: "雷达" },
    radar_switch: { label: "雷达开关" },
    reactive_energy: { label: "无功电量" },
    refresh: { label: "刷新" },
    refresh_rate: { label: "刷新频率" },
    region_occupied: { label: "区域有人" },
    regulator_mode: { label: "调节模式" },
    relay: { label: "继电器" },
    restart: { label: "重启" },
    rfid: { label: "RFID" },
    ringtone: { label: "铃声" },
    rms_voltage: { label: "有效电压" },
    rssi: { label: "无线信号强度" },
    running_state: { label: "运行状态" },
    salinity: { label: "盐度" },
    scene: { label: "场景" },
    sceneid: { label: "场景 ID" },
    schedule: { label: "计划" },
    sensitivity: { label: "灵敏度" },
    serial_number: { label: "序列号" },
    setpoint_change_source: { label: "设定值变更来源" },
    simulated_brightness: { label: "模拟亮度", description: "非调光设备通过闪烁模拟亮度调节" },
    settings: { label: "设置" },
    side: { label: "面/方向" },
    silent_mode: { label: "静音模式" },
    signed_power: { label: "带符号功率" },
    siren_and_light: { label: "声光报警" },
    smoke: { label: "烟雾报警" },
    soil_moisture: { label: "土壤湿度" },
    sos: { label: "SOS 报警" },
    sound: { label: "声音" },
    sound_volume: { label: "音量" },
    speed: { label: "速度" },
    state: { label: "开关状态" },
    state_action: { label: "状态动作" },
    state_left: { label: "左键状态" },
    state_l1: { label: "一路状态" },
    state_l2: { label: "二路状态" },
    state_l3: { label: "三路状态" },
    state_right: { label: "右键状态" },
    strength: { label: "强度" },
    switch: { label: "开关" },
    switch_type: { label: "开关类型" },
    system_mode: { label: "系统模式" },
    tamper: { label: "防拆报警" },
    tank_level: { label: "水箱液位" },
    target_distance: { label: "目标距离" },
    tds: { label: "TDS" },
    temperature: { label: "温度" },
    temperature_alarm: { label: "温度报警" },
    temperature_calibration: { label: "温度校准" },
    temperature_offset: { label: "温度补偿" },
    temperature_precision: { label: "温度精度" },
    temperature_scale: { label: "温度单位" },
    temperature_setpoint: { label: "设定温度" },
    test: { label: "测试" },
    testing: { label: "测试中" },
    thermostat_unit: { label: "温控器温度单位" },
    th_heater: { label: "防凝露加热", description: "传感器防凝露加热器" },
    total_number: { label: "总次数" },
    tilt: { label: "倾斜角" },
    timer: { label: "定时器" },
    timestamp: { label: "时间戳" },
    toggle: { label: "切换" },
    transition: { label: "过渡时间" },
    trouble: { label: "异常" },
    uart_baud_rate: { label: "UART 波特率" },
    uart_connection: { label: "UART 连接状态" },
    under_voltage: { label: "欠压" },
    update: { label: "固件更新" },
    update_frequency: { label: "更新频率" },
    uptime: { label: "运行时长" },
    vacancy: { label: "无人状态" },
    vacant: { label: "空闲/无人" },
    valve: { label: "阀门" },
    valve_state: { label: "阀门状态" },
    vibration: { label: "振动" },
    vibration_timeout: { label: "振动清除延迟" },
    voltage: { label: "电压" },
    voc: { label: "VOC" },
    volume: { label: "音量" },
    warm_floor: { label: "地暖" },
    warming_up: { label: "预热中" },
    water: { label: "水" },
    water_consumed: { label: "用水量" },
    water_leak: { label: "漏水报警" },
    water_total_reset: { label: "重置用水总量" },
    watering: { label: "浇水" },
    watt: { label: "瓦特" },
    wifi: { label: "Wi-Fi" },
    window: { label: "窗户" },
    window_detection: { label: "开窗检测" },
    window_open: { label: "窗户打开" },
    window_open_mode: { label: "开窗模式" },
};

function normalizeKey(key: string): string {
    return key.trim().replaceAll("-", "_");
}

export function getSemanticLabel(key: string | undefined, fallback?: string): SemanticLabel & { originalKey: string } {
    const originalKey = key ?? "";
    const normalizedKey = normalizeKey(originalKey);
    const label = LABELS[normalizedKey] ?? LABELS[normalizedKey.toLowerCase()];
    const tuyaDatapointMatch = normalizedKey.match(/^tuya_dp_(\d+)(?:_type)?$/);

    if (label) {
        return { ...label, originalKey };
    }

    if (tuyaDatapointMatch) {
        return {
            label: normalizedKey.endsWith("_type") ? `Tuya DP ${tuyaDatapointMatch[1]} 数据类型` : `未识别 Tuya DP ${tuyaDatapointMatch[1]}`,
            description: "外部转换器尚未语义化的 Tuya 原始数据点",
            originalKey,
        };
    }

    return {
        label: fallback || startCase(originalKey || "unknown"),
        originalKey,
    };
}

export function getSemanticTitle(key: string | undefined, fallback?: string): string {
    const semantic = getSemanticLabel(key, fallback);

    return semantic.originalKey ? `${semantic.label}（原始字段：${semantic.originalKey}）` : semantic.label;
}
